### ISSUE TITLE
Site returns http 520 due to cloudflared

### ISSUE THREAD

**Issue by shruuub** [Tech1k/hellopico#2]
Hi,
Visiting the site currently returns
```
502 Bad Gateway
Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared
```
Just wanted to let you know :)

**Comment by Tech1k** [comment]
Hello shruuub,

I appreciate you bringing this to my attention and I am aware of this. What's most likely happening is that the limited memory on the pico gets used up over time and causes it to become unresponsive and crash. Thus, making it not respond to any connections and the Cloudflare error is due to the tunnel not being able to connect to the pico when this occurs. To fix this, I am implementing a software reset (restart) to automatically run on one of the 2 cores most likely every hour to clear the memory and allow it to keep running smoothly.
